[package]
name = "desune-counter-backend"
version = "0.1.0"
authors = ["3c1u (Hikaru Terazono) <3c1u@vulpesgames.tokyo>"]
edition = "2018"

[dependencies]
actix-web = "2.0.0"
actix-rt = "1.0.0"
serde = { version = "1.0.104", features = ["derive"] }
tokio-postgres = "0.5.1"
tokio = "1.18.5"
